name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: |
        updated=$(date +%s)
        docker build . -t peterwest86/jobjack-server:$updated
        docker tag peterwest86/jobjack-server:$updated peterwest86/jobjack-server:latest
    - name: Docker Push
      run: docker push peterwest86/jobjack-server
